server:
  port: 8081

logging:
  level:
    io:
      itpl:
        auth: TRACE

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb
      database: auth-service
      auto-index-creation: true
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
#      client:
#        registration:
#          api-client-oidc:
#            provider: spring
#            client-id: api-client
#            client-secret: secret
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
#            scope: openid
#            client-name: api-client-oidc
#          api-client-authorization-code:
#            provider: spring
#            client-id: api-client
#            client-secret: secret
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://localhost:8080/authorized"
#            scope: api.read
#            client-name: api-client-authorization-code
#        provider:
#          spring:
#            issuer-uri: http://localhost:8081
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks

# Micrometer configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"

